export const SkillData = [
    {
        name: "Html 5",
        Image: "/Portfolio/icons/html.svg",
        width: 100,
        height: 80,
    },
    {
        name: "Css",
        Image: "/Portfolio/icons/css.svg",
        width: 100,
        height: 80,
    },
    {
        name: "JavaScript",
        Image: "/Portfolio/icons/js.svg",
        width: 100,
        height: 65,
    },
    {
        name: "Tailwind Css",
        Image: "/Portfolio/icons/tailwind.svg",
        width: 100,
        height: 80,
    },
    {
        name: "React",
        Image: "/Portfolio/icons/react.svg",
        width: 100,
        height: 80,
    },
    {
        name: "Aws",
        Image: "/Portfolio/icons/aws.svg",
        width: 100,
        height: 80,
    },

    {
        name: "TypeScript",
        Image: "/Portfolio/icons/ts.svg",
        width: 100,
        height: 80,
    },
    {
        name: "Next",
        Image: "/Portfolio/icons/next.svg",
        width: 100,
        height: 80,
    },
    {
        name: "Redis",
        Image: "/Portfolio/icons/redis.svg",
        width: 100,
        height: 80,
    },
    {
        name: "Dart",
        Image: "/Portfolio/icons/dart.svg",
        width: 100,
        height: 80,
    },
    {
        name: "Node js",
        Image: "/Portfolio/icons/node.svg",
        width: 100,
        height: 80,
    },
    {
        name: "Mongo db",
        Image: "/Portfolio/icons/mongo.svg",
        width: 100,
        height: 80,
    },
    {
        name: "Rust",
        Image: "/Portfolio/icons/rust.svg",
        width: 100,
        height: 80,
    },
    {
        name: "Sentry",
        Image: "/Portfolio/icons/sentry.svg",
        width: 100,
        height: 80,
    },
    {
        name: "Figma",
        Image: "/Portfolio/icons/figma.svg",
        width: 80,
        height: 80,
    },
    {
        name: "Python",
        Image: "/Portfolio/icons/python.svg",
        width: 100,
        height: 80,
    },
    {
        name: "PostgreSQL",
        Image: "/Portfolio/icons/psql.svg",
        width: 100,
        height: 80,
    },
    {
        name: "Nginx",
        Image: "/Portfolio/icons/nginx.svg",
        width: 100,
        height: 80,
    },
    {
        name: "Linux",
        Image: "/Portfolio/icons/linux.svg",
        width: 100,
        height: 80,
    },
    {
        name: "Docker",
        Image: "/Portfolio/icons/docker.svg",
        width: 100,
        height: 80,
    },
    {
        name: "Git",
        Image: "/Portfolio/icons/git.svg",
        width: 100,
        height: 80,
    },
];

export const projects = [
    {
        id: '1',
        image: '/Portfolio/imgs/dowhile.png',
        title: 'DoWhile',
        description: 'I actively participated in the development of a full-stack application for the DoWhile 2021 event, featuring real-time communication. Crafted during the Rocketseat NLW, we utilized socket.io to establish asynchronous communication with the server, implementing the async/await concept. An engaging experience, integrating technologies to achieve effective communication within the event context.',
        tecnologies: ['ReactJS', 'TypeScript', 'Styled Components', 'NodeJS', 'Prisma', 'Socket.io', 'React Native', 'Framer Motion', 'Moti', 'Elixir'],
    },
    {
        id: '2',
        image: '/Portfolio/imgs/podcastr.png',
        title: 'Podcastr',
        description: 'Podcastr stands as a robust and comprehensive platform meticulously crafted to cater to the dynamic world of podcast broadcasting. This innovative and user-friendly platform serves as a haven for both seasoned podcasters and aspiring individuals looking to venture into the captivating realm of digital audio content creation.',
        tecnologies: ['Reactjs', 'Axios', 'date-fns', 'Next', 'Sass', 'NodeJS', 'TypeScript', 'json-server'],
    },
    {
        id: '3',
        image: '/Portfolio/imgs/whereisthephp.jpg',
        title: 'WhereIsThePhp',
        description: 'Actively engaged in a Banco BTG onsite hackathon, I, along with three colleagues, spearheaded the development of the back-end for an impromptu application. We devised an innovative solution enabling users to use their dividends for bill payments, implementing queues and messaging for process optimization. An intense and rewarding experience, blending creativity and technical skills to tackle a real challenge in the financial sector.',
        tecnologies: ['Typescript', 'Vue', 'NodeJs', 'BullMQ', 'ExpressJs', 'Prisma', 'Docker', 'MySQL'],
    },
    {
        id: '4',
        image: '/Portfolio/imgs/project-devmenthors.jpg',
        title: 'DevMenthors',
        description: 'For a year, I contributed to the "DevMentors" project, teaching back-end programming, covering topics from basic routing to advanced concepts like databases, caching, and RabbitMQ messaging. We also delved into Docker container orchestration and application deployment, offering students practical insights into scalable development. This experience enriched both myself and the community, fostering collaboration and inspiration.',
        tecnologies: ['Typescript', 'Docker', 'NodeJs', 'ExpressJs', 'Vitest', 'Prisma', 'Redis', 'SQLite'],
    },
];